### ISSUE TITLE
Not able to flash Wifi firmware via M997 S1

### ISSUE THREAD

**Issue by disneytoy** [TeamGloomy/ender-3-fly-E3#1]
Greetings,

I am stuck at flashing the firmware for the Fly E3 wifi. Everything is freshly downloaded. I've tried 3 SD card. I've done deep formats on a couple. I even redownloaded the DuetWiFiServer-stm32f4.bin (renamed to DuetWiFiServer.bin) Just to be safe because I've read different things, I have the bin in \firmware and \sys.

M997 S1
Successfully connects and erases. It starts uploading  then...

SDIO Read SD timeout
Error reading sector 24896 length 2

Now the specific sector reported does change based on the different SD cards. So I'm pretty sure it is not the cards themselves. Like I said, I even reformatted them and copied fresh files back on. Is the bin bad?

(https://github.com/gloomyandy/DuetWiFiSocketServer/releases/tag/V1.25-01)

(I did try YAT, PuTTY and Repetier Host)

Any ideas

Thanks.

 Max

--------------------

FIRMWARE_NAME: RepRapFirmware for STM32F4 based Boards FIRMWARE_VERSION: 3.3beta3_2 ELECTRONICS: STM32F4 FIRMWARE_DATE: 2021-04-28 12:29:03

12:15:40.444 : N23 M997 S1*87

12:15:43.553 : Trying to connect at 230400 baud:  success
12:15:43.570 : Erasing 4096 bytes...
12:15:43.622 : Erasing 278528 bytes...
12:15:44.832 : Uploading file...
12:15:49.847 : SDIO Read SD timeout
12:15:49.847 : Error reading sector 24896 length 2
12:15:54.867 : SDIO Read SD timeout
12:15:54.867 : Error reading sector 24896 length 2
12:15:59.907 : SDIO Read SD timeout
12:15:59.907 : Error reading sector 24896 length 2

**Comment by jaysuk** [comment]
There's a bug in 3.3b2. Downgrade to 3.3b1_6, flash the firmware, then
upgrade

**Comment by disneytoy** [comment]
Thanks Jay!  

You are great!

That worked. By any chance, do you know where in the settings I can change the printer type from Cartesian to Polar? 

In the config tool they only show:    Cartesian     CoreXY     CoreXZ      Delta

I'm experimenting with a polar printer and that is why I got the Fly.  Thanks again!!!

Max

**Comment by gloomyandy** [comment]
@disneytoy Please use our discord server (see the wiki for details) for support questions.

**Comment by jaysuk** [comment]
M669 changes the kinematics

**Comment by jaysuk** [comment]
this was fixed in 3.3b3
